# NumPy Tutorial

- NumPy is short for "Numerical Python".
- NumPy is a Python library used for working with arrays.
- It also has functions for working in domain of linear algebra, fourier transform, and matrices.
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [1]:
import numpy as np

In [2]:
arr_l = np.array([1, 2, 3, 4, 5])
arr_t = np.array((1, 2, 3, 4, 5))

print(arr_l)
print(arr_t)

[1 2 3 4 5]
[1 2 3 4 5]


The array object in NumPy is called $\textit{ndarray}$.

In [3]:
print(type(arr_l))
print(type(arr_t))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [4]:
print(np.arange(75))
print()
print(np.arange(60,75))
print()
print(np.arange(60,75,5))

print()

print(np.linspace(10,22)) # num=50 (default)
print()
print(np.linspace(10,22,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74]

[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]

[60 65 70]

[10.         10.24489796 10.48979592 10.73469388 10.97959184 11.2244898
 11.46938776 11.71428571 11.95918367 12.20408163 12.44897959 12.69387755
 12.93877551 13.18367347 13.42857143 13.67346939 13.91836735 14.16326531
 14.40816327 14.65306122 14.89795918 15.14285714 15.3877551  15.63265306
 15.87755102 16.12244898 16.36734694 16.6122449  16.85714286 17.10204082
 17.34693878 17.59183673 17.83673469 18.08163265 18.32653061 18.57142857
 18.81632653 19.06122449 19.30612245 19.55102041 19.79591837 20.04081633
 20.28571429 20.53061224 20.7755102  21.02040816 21.26530612 21.51020408
 21.75510204 22.        ]

[10. 13. 16. 19. 22.]


## Creating Arrays

In [5]:
arr = np.array(42)

print(arr)
print()
print("arr*2: \n", arr*2)
print()
print('Number of Dimensions:', arr.ndim)

42

arr*2: 
 84

Number of Dimensions: 0


In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print()
print("arr^2: \n", arr**2)
print()
print('Number of Dimensions:', arr.ndim)

[1 2 3 4 5]

arr^2: 
 [ 1  4  9 16 25]

Number of Dimensions: 1


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print()
print("arr/3: \n", arr/2)
print()
print('Number of Dimensions:', arr.ndim)

[[1 2 3]
 [4 5 6]]

arr/3: 
 [[0.5 1.  1.5]
 [2.  2.5 3. ]]

Number of Dimensions: 2


In [8]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)
print()
print("arr%5: \n", arr%5)
print()
print('Number of Dimensions:', arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

arr%5: 
 [[[1 2 3]
  [4 0 1]]

 [[2 3 4]
  [0 1 2]]]

Number of Dimensions: 3


## Array Indexing

### 1D-Array

In [9]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [10]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### 2D-Array

In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('Last element from 2nd dim: ', arr[1, -1])

2nd element on 1st row:  2
Last element from 2nd dim:  10


### 3D-Array

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


## Array Slicing

### Slicing 1-D Arrays

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Slice elements from index 1 to index 5
print(arr[1:5])
# Slice elements from index 4 to the end of the array
print(arr[4:])
# Slice elements from the beginning to index 4 (not included)
print(arr[:4])
# Slice from the index 3 from the end to index 1 from the end
print(arr[-3:-1])

print(arr[1:5:2])
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


### Slicing 2-D Arrays

In [14]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


## Copy vs View

The main difference between a **copy** and a **view** of an array is that the **copy is a new array**, and the **view is just a view of the original array**.

- The **copy** owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The **view** does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [15]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


**copies owns the data**, and **views does not own the data**, but how can we check this?

Every NumPy array has the attribute **base** that **returns None if the array owns the data Otherwise, the base  attribute refers to the original object.**

In [18]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## Array Shape & Reshape

In [19]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


**Can We Reshape Into any Shape?**

Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View?

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


The example above returns the original array, so it is a $\textit{view}$.

### Unknown Dimension

You are allowed to have one "unknown" dimension. Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method. Pass -1 as the value, and NumPy will calculate this number for you.

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)
print(newarr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


**Note:** We can not pass -1 to more than one dimension.

### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array. We can use $\textit{reshape(-1)}$ to do this.

In [25]:
vector = np.array([1,2,3,4,5,6,7,8,9])
matrix = np.array([[1,2,3], [4,5,6]])
tensor = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

newVector = vector.reshape(-1)
newMatrix = matrix.reshape(-1)
newTensor = tensor.reshape(-1)

print(newVector)
print()
print(newMatrix)
print()
print(newTensor)

[1 2 3 4 5 6 7 8 9]

[1 2 3 4 5 6]

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Array Iterating

In [26]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [30]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

In [31]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [32]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr[:, ::2])
print()

for x in np.nditer(arr[:, ::2]):
    print(x)

[[1 3]
 [5 7]]

1
3
5
7


### Enumerated Iteration Using ndenumerate()

In [33]:
arr = np.array([[1, 2, 3],[4, 5, 6]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## Array Join

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Array Split

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [36]:
arr1, arr2, arr3 = newarr

print('arr1:', arr1)
print('arr2:', arr2)
print('arr3:', arr3)

arr1: [1 2]
arr2: [3 4]
arr3: [5 6]


If the array has less elements than required, it will adjust from the end accordingly.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Splitting 2D Arrays

In [38]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [39]:
arr1, arr2, arr3 = newarr

print('arr1: \n', arr1)
print('arr2: \n', arr2)
print('arr3: \n', arr3)

arr1: 
 [[1 2]
 [3 4]]
arr2: 
 [[5 6]
 [7 8]]
arr3: 
 [[ 9 10]
 [11 12]]


you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the row (axis=1).

## Array Search

You can search an array for a certain value, and return the indexes that get a match.

In [40]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


## Array Sort

In [42]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))
print(arr)

[0 1 2 3]
[3 2 0 1]


In [43]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(arr)

['apple' 'banana' 'cherry']
['banana' 'cherry' 'apple']


**Note:** Unlike lists, this method returns a copy of the array, leaving the original array unchanged.

In [44]:
List = [3, 2, 0, 1]
arr = np.array([3, 2, 0, 1])

List.sort()
print(List)

print()

np.sort(arr)
print(arr)

[0, 1, 2, 3]

[3 2 0 1]


If you use the sort() method on a 2-D array, both arrays will be sorted

In [45]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


## Array Filter

In [46]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [47]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [48]:
arr > 42

array([False, False,  True,  True])

In [49]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
